### ISSUE TITLE
both bar plot and average are not handled in 1 command

### ISSUE THREAD

**Issue by Ujjval-Patel** [kaustubhhiware/rose#24]
Can we add functionality such that both we can run something like
`python3 scrape_views.py -i -a -b suits` 
as a first time user that was my first command and I think many people would prefer to have both functionalities in the same command, right now after executing this command, the program gave the result of `-b` and became irresponsive afterward.

**Comment by kaustubhhiware** [comment]
Are you sure both the commands don't work together ?
The command seems to execute perfectly in my system, as well as if you have a look at the scrape_views' [line 329](https://github.com/kaustubhhiware/rose/blob/master/scrape_views.py#L329), both are non-blocking, that is they can be executed together.

Closing this issue because of the aforementioned reasons. Please feel free to reopen it / comment here if issue still persists.
