### ISSUE TITLE
WebApp: The bargraph and averages take forever to load.

### ISSUE THREAD

**Issue by vishaaaljagtap** [kaustubhhiware/rose#31]
![screenshot from 2019-02-06 15-22-31](https://user-images.githubusercontent.com/41343491/52333389-25541480-2a23-11e9-9075-acd0f6fed597.png)

**Comment by kaustubhhiware** [comment]
Thanks for bringing this to my attention, @vishaaaljagtap.

This is a known issue (#5) , which was available for a winter of code program. However the person assigned to this issue gave up and there is nothing I could do about it.

Currently static images are being served which is possibly the worst software practice, however it was also another beginner PR so was thus accepted. The solution is to have plots via d3, plotly or similar modules - which is simple thus left open for beginner contributions. 

Closing since this is a version of #5.
